// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVEfYmN4qlv8J8iPL5V0FCRU47wHoDkM',
    appId: '1:818156194647:web:04bb3298e151c2d69a8c12',
    messagingSenderId: '818156194647',
    projectId: 'lostandfound-e7a1d',
    authDomain: 'lostandfound-e7a1d.firebaseapp.com',
    storageBucket: 'lostandfound-e7a1d.firebasestorage.app',
    measurementId: 'G-19ND4R0D1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBICCBv5Ngk3-xx-s4A3n0YPrqzFz28RR4',
    appId: '1:818156194647:android:b0a471bcedfadf3c9a8c12',
    messagingSenderId: '818156194647',
    projectId: 'lostandfound-e7a1d',
    storageBucket: 'lostandfound-e7a1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN8VTUIjjhPogUJ_ymVNyMB0mxHNkbQa4',
    appId: '1:818156194647:ios:052dbad0814c8c799a8c12',
    messagingSenderId: '818156194647',
    projectId: 'lostandfound-e7a1d',
    storageBucket: 'lostandfound-e7a1d.firebasestorage.app',
    iosClientId: '818156194647-tqc0omucuf3qj0bp5ua8vnumhfidmcka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN8VTUIjjhPogUJ_ymVNyMB0mxHNkbQa4',
    appId: '1:818156194647:ios:052dbad0814c8c799a8c12',
    messagingSenderId: '818156194647',
    projectId: 'lostandfound-e7a1d',
    storageBucket: 'lostandfound-e7a1d.firebasestorage.app',
    iosClientId: '818156194647-tqc0omucuf3qj0bp5ua8vnumhfidmcka.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzVEfYmN4qlv8J8iPL5V0FCRU47wHoDkM',
    appId: '1:818156194647:web:17d0acb9e913e1769a8c12',
    messagingSenderId: '818156194647',
    projectId: 'lostandfound-e7a1d',
    authDomain: 'lostandfound-e7a1d.firebaseapp.com',
    storageBucket: 'lostandfound-e7a1d.firebasestorage.app',
    measurementId: 'G-BM2E975LH2',
  );
}
